<?php

declare(strict_types=1);

namespace LBHurtado\XChange\Services;

use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

class PublishedAssetDriftDetector
{
    public const string GeneratedHeaderId = 'AUTO-GENERATED BY x-change:install';

    /**
     * @return array<string, string>
     */
    public function cockpitMappings(): array
    {
        return [
            $this->packagePath('resources/js/cockpit') => resource_path('js/cockpit'),
            $this->packagePath('resources/js/pages/x-change/cockpit') => resource_path('js/pages/x-change/cockpit'),
        ];
    }

    /**
     * @param  array<string, string>|null  $mappings
     * @return array{
     *     name: string,
     *     passed: bool,
     *     message: string,
     *     summary: array{checked: int, ok: int, stale: int, missing: int, extra: int},
     *     files: array<int, array{status: string, source: string|null, target: string|null, relative_path: string, reason: string}>
     * }
     */
    public function inspect(?array $mappings = null): array
    {
        $files = [];
        $summary = [
            'checked' => 0,
            'ok' => 0,
            'stale' => 0,
            'missing' => 0,
            'extra' => 0,
        ];

        foreach ($mappings ?? $this->cockpitMappings() as $sourceRoot => $targetRoot) {
            $sourceFiles = $this->filesByRelativePath($sourceRoot);
            $targetFiles = $this->filesByRelativePath($targetRoot);

            foreach ($sourceFiles as $relativePath => $sourcePath) {
                $summary['checked']++;
                $targetPath = $targetFiles[$relativePath] ?? null;

                if ($targetPath === null) {
                    $summary['missing']++;
                    $files[] = $this->fileResult('missing', $sourcePath, $targetRoot.'/'.$relativePath, $relativePath, 'published file is missing');

                    continue;
                }

                if ($this->normalizeContents(file_get_contents($sourcePath) ?: '') !== $this->normalizeContents($this->stripGeneratedHeader(file_get_contents($targetPath) ?: ''))) {
                    $summary['stale']++;
                    $files[] = $this->fileResult('stale', $sourcePath, $targetPath, $relativePath, 'published file differs from package source');

                    continue;
                }

                $summary['ok']++;
                $files[] = $this->fileResult('ok', $sourcePath, $targetPath, $relativePath, 'published file matches package source');
            }

            foreach ($targetFiles as $relativePath => $targetPath) {
                if (array_key_exists($relativePath, $sourceFiles)) {
                    continue;
                }

                $summary['checked']++;
                $summary['extra']++;
                $files[] = $this->fileResult('extra', null, $targetPath, $relativePath, 'published file has no package source counterpart');
            }
        }

        $passed = $summary['stale'] === 0
            && $summary['missing'] === 0
            && $summary['extra'] === 0;

        return [
            'name' => 'published cockpit assets',
            'passed' => $passed,
            'message' => $passed
                ? 'published Cockpit assets match package source'
                : 'published Cockpit assets have drift from package source',
            'summary' => $summary,
            'files' => $files,
        ];
    }

    /**
     * @param  array<string, string>|null  $mappings
     * @return array{updated: int, skipped: int, files: array<int, array{source: string, target: string, relative_path: string}>}
     */
    public function applyGeneratedHeaders(?array $mappings = null): array
    {
        $updated = 0;
        $skipped = 0;
        $files = [];

        foreach ($mappings ?? $this->cockpitMappings() as $sourceRoot => $targetRoot) {
            foreach ($this->filesByRelativePath($sourceRoot) as $relativePath => $sourcePath) {
                $targetPath = $targetRoot.'/'.$relativePath;

                if (! is_file($targetPath)) {
                    $skipped++;

                    continue;
                }

                $contents = file_get_contents($sourcePath) ?: '';
                $currentTargetContents = file_get_contents($targetPath) ?: '';

                if ($this->normalizeContents($contents) !== $this->normalizeContents($this->stripGeneratedHeader($currentTargetContents))) {
                    $skipped++;

                    continue;
                }

                $targetContents = $this->withGeneratedHeader($contents, $relativePath);

                if (! is_dir(dirname($targetPath))) {
                    mkdir(dirname($targetPath), 0777, true);
                }

                file_put_contents($targetPath, $targetContents);

                $updated++;
                $files[] = [
                    'source' => $sourcePath,
                    'target' => $targetPath,
                    'relative_path' => $relativePath,
                ];
            }
        }

        return [
            'updated' => $updated,
            'skipped' => $skipped,
            'files' => $files,
        ];
    }

    public function withGeneratedHeader(string $contents, string $relativePath): string
    {
        $contents = $this->stripGeneratedHeader($contents);
        $header = str_ends_with($relativePath, '.vue')
            ? $this->htmlHeader($relativePath)
            : $this->blockHeader($relativePath);

        return $header.$contents;
    }

    public function stripGeneratedHeader(string $contents): string
    {
        $id = preg_quote(self::GeneratedHeaderId, '/');

        $contents = preg_replace('/\A<!--\R'.$id.'.*?-->\R?/s', '', $contents) ?? $contents;
        $contents = preg_replace('/\A\/\*\R \* '.$id.'.*?\*\/\R?/s', '', $contents) ?? $contents;

        return $contents;
    }

    protected function packagePath(string $path): string
    {
        return dirname(__DIR__, 2).'/'.ltrim($path, '/');
    }

    /**
     * @return array<string, string>
     */
    protected function filesByRelativePath(string $root): array
    {
        if (! is_dir($root)) {
            return [];
        }

        $files = [];
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($root, RecursiveDirectoryIterator::SKIP_DOTS)
        );

        /** @var SplFileInfo $file */
        foreach ($iterator as $file) {
            if (! $file->isFile() || $file->getFilename() === '.DS_Store') {
                continue;
            }

            $path = $file->getPathname();
            $relativePath = ltrim(str_replace('\\', '/', substr($path, strlen(rtrim($root, DIRECTORY_SEPARATOR)))), '/');

            $files[$relativePath] = $path;
        }

        ksort($files);

        return $files;
    }

    protected function normalizeContents(string $contents): string
    {
        return str_replace(["\r\n", "\r"], "\n", $contents);
    }

    /**
     * @return array{status: string, source: string|null, target: string|null, relative_path: string, reason: string}
     */
    protected function fileResult(string $status, ?string $source, ?string $target, string $relativePath, string $reason): array
    {
        return [
            'status' => $status,
            'source' => $source,
            'target' => $target,
            'relative_path' => $relativePath,
            'reason' => $reason,
        ];
    }

    protected function htmlHeader(string $relativePath): string
    {
        return <<<HTML
        <!--
        {$this->headerText($relativePath)}
        -->

        HTML;
    }

    protected function blockHeader(string $relativePath): string
    {
        return <<<TEXT
        /*
         * {$this->headerText($relativePath, "\n * ")}
         */

        TEXT;
    }

    protected function headerText(string $relativePath, string $linePrefix = "\n"): string
    {
        return self::GeneratedHeaderId.$linePrefix
            .$linePrefix
            .'Source: packages/x-change/resources/js/'.$relativePath.$linePrefix
            .$linePrefix
            .'Do not edit this published host copy directly.'.$linePrefix
            .'Changes will be overwritten by php artisan x-change:install --force.';
    }
}
