<script setup lang="ts">
import { Link, useForm } from '@inertiajs/vue3';
import { ArrowLeft, Check, Download, FileSpreadsheet, LockKeyhole, Plus, Send, Upload, Users, XCircle } from 'lucide-vue-next';
import { index } from '@/routes/x-change/cockpit/campaigns';
import rows from '@/routes/x-change/cockpit/campaigns/rows';
import imports from '@/routes/x-change/cockpit/campaigns/imports';
import authorizations from '@/routes/x-change/cockpit/campaigns/authorizations';
import fulfillments from '@/routes/x-change/cockpit/campaigns/fulfillments';
import exports from '@/routes/x-change/cockpit/campaigns/exports';
import { show as claimShow } from '@/routes/x-change/claim';
import CockpitLayout from '../layouts/CockpitLayout.vue';
import type { CockpitHeaderPageProps } from '../types';

type Row = { reference: string; ordinal: number; beneficiary: Record<string, string>; amount_minor: number; delivery_preference: string; status: string };
type Worksheet = { reference: string; profile: string; name: string; status: string; fulfillment_mode: string; rows: Row[] };
type Import = { reference: string; status: string; source_format: string; row_count: number; valid_count: number; validation_errors: { row: number; messages: string[] }[]; mapping: Record<string, string> };
type Authorization = { reference?: string; status?: string; approval_pay_code?: string | null; beneficiary_count?: number; principal_minor?: number };
type Fulfillment = { reference: string; ordinal: number; beneficiary: string; amount_minor: number; mode: string; status: string; provider_transfer_reference: string | null; pay_code: string | null };
type Props = CockpitHeaderPageProps & { worksheet: Worksheet; imports: Import[]; fulfillment_summary: Record<string, number>; authorization: Authorization; fulfillments: Fulfillment[] };
const props = defineProps<Props>();
const form = useForm({ amount_minor: null as number | null, name: '', mobile: '', bank_account: '', bank_code: '', email: '', remarks: '', external_reference: '', delivery_preference: 'manual' });
const importForm = useForm({ file: null as File | null });
const authorizationForm = useForm({});
const fulfillmentForm = useForm({});
const transferForm = useForm({});
const reconciliationForm = useForm({});
const fallbackForm = useForm({});
const peso = (minor: number) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(minor / 100);
const plannedCount = (): number => props.fulfillment_summary.planned_count ?? 0;
const fulfillmentReadinessDescription = (): string => {
    const count = plannedCount();

    if (count === 0) {
        return 'The authorized worksheet is preparing its beneficiary issuance plan. No Pay Codes, delivery, or bank transfers have started.';
    }

    return count + ' ' + (count === 1 ? 'beneficiary is' : 'beneficiaries are') + ' ready for explicit issuance. No Pay Codes, delivery, or bank transfers have started.';
};
const add = (): void => form.post(rows.store(props.worksheet.reference), { preserveScroll: true, onSuccess: () => form.reset() });
const stage = (): void => importForm.post(imports.store(props.worksheet.reference), { preserveScroll: true, onSuccess: () => importForm.reset() });
const apply = (reference: string): void => importForm.post(imports.apply({ worksheet: props.worksheet.reference, import: reference }), { preserveScroll: true });
const authorize = (): void => authorizationForm.post(authorizations.store(props.worksheet.reference), { preserveScroll: true });
const issue = (): void => fulfillmentForm.post(fulfillments.payCodes.store(props.worksheet.reference), { preserveScroll: true });
const dispatchTransfers = (): void => transferForm.post(fulfillments.bankTransfers.store(props.worksheet.reference), { preserveScroll: true });
const reconcileTransfers = (): void => reconciliationForm.post(fulfillments.bankTransfers.reconciliations.store(props.worksheet.reference), { preserveScroll: true });
const planFallbacks = (): void => fallbackForm.post(fulfillments.fallbacks.store(props.worksheet.reference), { preserveScroll: true });
</script>

<template>
    <CockpitLayout active-navigation="campaigns" :cockpit-header-read-model="props.cockpit_header_read_model">
        <main class="mx-auto max-w-7xl space-y-5" data-testid="cockpit-campaign-worksheet-page">
            <section class="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between dark:border-slate-800 dark:bg-slate-900">
                <div>
                    <Link :href="index()" class="inline-flex items-center gap-1 text-xs font-semibold text-slate-500 hover:text-slate-950 dark:text-slate-400 dark:hover:text-white"><ArrowLeft class="size-3.5" /> Campaigns</Link>
                    <p class="mt-2 text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">{{ props.worksheet.profile }} worksheet</p>
                    <h1 class="mt-0.5 text-xl font-semibold text-slate-950 dark:text-slate-50">{{ props.worksheet.name }}</h1>
                </div>
                <div class="rounded-xl bg-slate-50 px-4 py-2 text-right dark:bg-slate-950"><p class="text-xs text-slate-500 dark:text-slate-400">Beneficiaries</p><p class="text-lg font-semibold text-slate-950 dark:text-slate-50">{{ props.worksheet.rows.length }}</p></div>
            </section>

            <section class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_24rem]">
                <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
                    <div class="border-b border-slate-200 px-4 py-3 dark:border-slate-800"><p class="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Draft Beneficiaries</p><h2 class="mt-0.5 font-semibold text-slate-950 dark:text-slate-50">Private Worksheet</h2></div>
                    <div v-if="props.worksheet.rows.length === 0" class="flex min-h-64 flex-col items-center justify-center text-center"><Users class="size-8 text-slate-300 dark:text-slate-700" /><p class="mt-3 font-semibold text-slate-950 dark:text-slate-50">No beneficiaries yet</p><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Add the first recipient from the form.</p></div>
                    <div v-else class="divide-y divide-slate-200 dark:divide-slate-800"><article v-for="row in props.worksheet.rows" :key="row.reference" class="grid gap-2 px-4 py-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><p class="font-semibold text-slate-950 dark:text-slate-50">{{ row.beneficiary.name || row.beneficiary.mobile || row.beneficiary.bank_account }}</p><p class="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{{ row.beneficiary.mobile || row.beneficiary.bank_account }} · {{ row.delivery_preference }}</p></div><p class="font-semibold text-slate-950 dark:text-slate-50">{{ peso(row.amount_minor) }}</p></article></div>
                </div>

                <form class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900" @submit.prevent="add">
                    <div class="flex items-center gap-2"><Plus class="size-4 text-slate-500" /><div><p class="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Add Beneficiary</p><h2 class="mt-0.5 font-semibold text-slate-950 dark:text-slate-50">Recipient Details</h2></div></div>
                    <div class="mt-4 grid gap-3"><label class="grid gap-1 text-sm font-medium text-slate-700 dark:text-slate-200">Amount (centavos)<input v-model.number="form.amount_minor" type="number" min="1" class="rounded-lg border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label class="grid gap-1 text-sm font-medium text-slate-700 dark:text-slate-200">Name <input v-model="form.name" class="rounded-lg border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label class="grid gap-1 text-sm font-medium text-slate-700 dark:text-slate-200">Mobile Or Bank Destination <input v-model="form.mobile" placeholder="Mobile" class="rounded-lg border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950 dark:text-white" /><input v-model="form.bank_account" placeholder="Bank account" class="rounded-lg border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950 dark:text-white" /><input v-model="form.bank_code" placeholder="Bank code (for NetBank transfer)" class="rounded-lg border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label class="grid gap-1 text-sm font-medium text-slate-700 dark:text-slate-200">Remarks <textarea v-model="form.remarks" rows="2" class="rounded-lg border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label></div>
                    <p v-if="form.errors.mobile || form.errors.bank_account || form.errors.amount_minor" class="mt-2 text-xs text-rose-600 dark:text-rose-300">{{ form.errors.amount_minor || form.errors.mobile || form.errors.bank_account }}</p>
                    <button type="submit" :disabled="form.processing" class="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-3 py-2.5 text-sm font-semibold text-white disabled:opacity-60 dark:bg-slate-100 dark:text-slate-950">{{ form.processing ? 'Adding…' : 'Add Beneficiary' }}</button>
                    <p class="mt-2 text-center text-xs text-slate-500 dark:text-slate-400">Draft only. This does not authorize, issue, deliver, or transfer funds.</p>
                </form>
            </section>

            <section v-if="props.worksheet.status === 'draft'" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-2"><LockKeyhole class="size-4 text-slate-500" /><div><p class="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Officer Authorization</p><h2 class="mt-0.5 font-semibold text-slate-950 dark:text-slate-50">Freeze And Create Approval Pay Code</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Locks this worksheet and creates one zero-value Settlement Pay Code. It does not issue, deliver, or transfer beneficiary funds.</p></div></div><button type="button" :disabled="props.worksheet.rows.length === 0 || authorizationForm.processing" class="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60 dark:bg-slate-100 dark:text-slate-950" @click="authorize"><LockKeyhole class="size-4" /> {{ authorizationForm.processing ? 'Creating…' : 'Create Approval Pay Code' }}</button></div>
            </section>
            <section v-if="props.worksheet.status === 'authorized' && props.worksheet.fulfillment_mode === 'pay_code_distribution'" data-testid="campaign-fulfillment-readiness" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Beneficiary Fulfillment</p><h2 class="mt-0.5 font-semibold text-slate-950 dark:text-slate-50">{{ plannedCount() > 0 ? 'Beneficiaries Ready To Issue' : 'Beneficiary Fulfillment Is Being Prepared' }}</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">{{ fulfillmentReadinessDescription() }}</p></div><div class="flex gap-2"><a :href="exports.payCodes(props.worksheet.reference).url" class="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200"><Download class="size-4" /> Export</a><button type="button" :disabled="plannedCount() === 0 || fulfillmentForm.processing" class="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60 dark:bg-slate-100 dark:text-slate-950" @click="issue"><Send class="size-4" /> {{ fulfillmentForm.processing ? 'Issuing…' : 'Issue Next 100' }}</button></div></div></section>
            <section v-if="props.worksheet.status === 'authorized' && props.worksheet.fulfillment_mode === 'direct_bank_transfer'" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">NetBank Fulfillment</p><h2 class="mt-0.5 font-semibold text-slate-950 dark:text-slate-50">Dispatch Next 100 Transfers</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Requires the explicit NetBank runtime gate. Checking never re-dispatches a transfer.</p></div><div class="flex flex-wrap gap-2"><a v-if="(props.fulfillment_summary.issued_count ?? 0) > 0" :href="exports.payCodes(props.worksheet.reference).url" class="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200"><Download class="size-4" /> Export Pay Codes</a><button v-if="(props.fulfillment_summary.fallback_count ?? 0) > 0" type="button" :disabled="fulfillmentForm.processing" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-semibold dark:border-slate-700" @click="issue">{{ fulfillmentForm.processing ? 'Issuing…' : 'Issue Planned Fallbacks' }}</button><button type="button" :disabled="fallbackForm.processing" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-semibold dark:border-slate-700" @click="planFallbacks">{{ fallbackForm.processing ? 'Planning…' : 'Plan Pay Code Fallbacks' }}</button><button type="button" :disabled="reconciliationForm.processing" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-semibold dark:border-slate-700" @click="reconcileTransfers">{{ reconciliationForm.processing ? 'Checking…' : 'Check NetBank' }}</button><button type="button" :disabled="transferForm.processing" class="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60 dark:bg-slate-100 dark:text-slate-950" @click="dispatchTransfers"><Send class="size-4" /> {{ transferForm.processing ? 'Dispatching…' : 'Dispatch Next 100' }}</button></div></div></section>
            <section v-if="props.worksheet.status === 'authorized'" class="grid grid-cols-2 gap-3 sm:grid-cols-4"><div v-for="[label, value] in [['Planned', props.fulfillment_summary.planned_count ?? 0], ['Issued', props.fulfillment_summary.issued_count ?? 0], ['Provider Ready', props.fulfillment_summary.provider_ready_count ?? 0], ['Pay Code Fallback', props.fulfillment_summary.fallback_count ?? 0]]" :key="label" class="rounded-xl border border-slate-200 bg-white px-3 py-2.5 dark:border-slate-800 dark:bg-slate-900"><p class="text-xs text-slate-500 dark:text-slate-400">{{ label }}</p><p class="mt-1 text-lg font-semibold text-slate-950 dark:text-slate-50">{{ value }}</p></div></section>
            <section v-if="props.authorization.status === 'awaiting_officer' && props.authorization.approval_pay_code" class="rounded-2xl border border-amber-200 bg-amber-50 p-4 shadow-sm dark:border-amber-900/70 dark:bg-amber-950/30"><p class="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-amber-800 dark:text-amber-200">Officer Authorization</p><div class="mt-1 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold text-slate-950 dark:text-slate-50">Approval Pay Code Ready</h2><p class="mt-1 text-sm text-slate-600 dark:text-slate-300">{{ props.authorization.approval_pay_code }} authorizes this frozen beneficiary list. It does not issue, deliver, or transfer beneficiary funds.</p></div><Link :href="claimShow(props.authorization.approval_pay_code)" class="inline-flex shrink-0 items-center justify-center rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-slate-100 dark:text-slate-950">Open Approval Pay Code</Link></div></section>
            <section v-if="props.fulfillments.length > 0" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-col gap-3 border-b border-slate-200 px-4 py-3 sm:flex-row sm:items-center sm:justify-between dark:border-slate-800"><div><p class="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Beneficiary Outcomes</p><h2 class="mt-0.5 font-semibold text-slate-950 dark:text-slate-50">First 100 Results</h2></div><a :href="exports.results(props.worksheet.reference).url" class="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200"><Download class="size-4" /> Export All Results</a></div><div class="divide-y divide-slate-200 dark:divide-slate-800"><article v-for="item in props.fulfillments" :key="item.reference" class="grid gap-2 px-4 py-3 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center"><div><p class="font-semibold text-slate-950 dark:text-slate-50">{{ item.ordinal }} · {{ item.beneficiary }}</p><p class="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{{ item.mode }} · {{ item.status }}<template v-if="item.provider_transfer_reference"> · {{ item.provider_transfer_reference }}</template><template v-else-if="item.pay_code"> · {{ item.pay_code }}</template></p></div><p class="text-sm font-semibold text-slate-950 dark:text-slate-50">{{ peso(item.amount_minor) }}</p><span class="w-fit rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{{ item.status }}</span></article></div></section>

            <section class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_24rem]">
                <div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                    <div class="flex items-center gap-2"><FileSpreadsheet class="size-4 text-slate-500" /><div><p class="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Import Review</p><h2 class="mt-0.5 font-semibold text-slate-950 dark:text-slate-50">Staged Beneficiaries</h2></div></div>
                    <p v-if="props.imports.length === 0" class="mt-4 text-sm text-slate-500 dark:text-slate-400">Upload a CSV or XLSX file to preview its detected fields and validation results.</p>
                    <div v-else class="mt-4 space-y-3"><article v-for="item in props.imports" :key="item.reference" class="rounded-xl border border-slate-200 p-3 dark:border-slate-800"><div class="flex items-start justify-between gap-3"><div><p class="font-semibold text-slate-950 dark:text-slate-50">{{ item.source_format.toUpperCase() }} import</p><p class="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{{ item.valid_count }} valid of {{ item.row_count }} rows · {{ item.status }}</p></div><button v-if="item.status === 'staged' && item.validation_errors.length === 0" type="button" class="inline-flex items-center gap-1 rounded-lg bg-slate-950 px-2.5 py-1.5 text-xs font-semibold text-white dark:bg-slate-100 dark:text-slate-950" @click="apply(item.reference)"><Check class="size-3.5" /> Apply Valid Rows</button></div><p v-if="item.validation_errors.length" class="mt-2 flex items-center gap-1 text-xs text-rose-600 dark:text-rose-300"><XCircle class="size-3.5" /> Row {{ item.validation_errors[0].row }}: {{ item.validation_errors[0].messages.join(' ') }}</p><p v-else class="mt-2 text-xs text-emerald-700 dark:text-emerald-300">Detected: {{ Object.entries(item.mapping).map(([field, header]) => `${header} → ${field}`).join(' · ') }}</p></article></div>
                </div>
                <form class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900" @submit.prevent="stage"><div class="flex items-center gap-2"><Upload class="size-4 text-slate-500" /><div><p class="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Import File</p><h2 class="mt-0.5 font-semibold text-slate-950 dark:text-slate-50">CSV Or XLSX</h2></div></div><input accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="file" class="mt-4 block w-full text-sm text-slate-600 dark:text-slate-300" @input="importForm.file = ($event.target as HTMLInputElement).files?.[0] ?? null" /><p v-if="importForm.errors.file" class="mt-2 text-xs text-rose-600">{{ importForm.errors.file }}</p><button type="submit" :disabled="!importForm.file || importForm.processing" class="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-3 py-2.5 text-sm font-semibold text-white disabled:opacity-60 dark:bg-slate-100 dark:text-slate-950">{{ importForm.processing ? 'Staging…' : 'Preview Import' }}</button><p class="mt-2 text-center text-xs text-slate-500 dark:text-slate-400">Nothing joins the draft until Apply Valid Rows is selected.</p></form>
            </section>
        </main>
    </CockpitLayout>
</template>
