<?php

return [
    'enabled' => (bool) env('PIPEDREAM_AUI_POLICY_COMPLETION_ENABLED', false),
    'token' => env('PIPEDREAM_AUI_POLICY_COMPLETION_TOKEN'),
    'disposition' => [
        'schema' => 'x-change.policy-completion-transport-disposition.v1',
        'enabled' => true,
        'accepted' => true,
        'driver_id' => 'aui.personal-accident.provisional-cover',
        'driver_version' => '1.0.0',
        'provider' => 'pipedream-test',
        'contract_id' => 'aui-demonstration-policy-completion',
        'contract_version' => '1.0.0',
        'submission_endpoint' => env('PIPEDREAM_AUI_POLICY_COMPLETION_ENDPOINT', ''),
        'authentication_scheme' => 'bearer-token',
        'request_schema_reference' => 'x-change.aui-demonstration-policy-transport-request.v1',
        'request_schema_version' => '1.0.0',
        'request_schema_digest' => 'sha256:'.hash_file('sha256', base_path('vendor/3neti/x-change/resources/policy-completion-contracts/aui-demonstration-policy-transport-request-v1.schema.json')),
        'response_schema_reference' => 'x-change.aui-demonstration-policy-response.v1',
        'response_schema_version' => '1.0.0',
        'response_schema_digest' => 'sha256:'.hash_file('sha256', base_path('vendor/3neti/x-change/resources/policy-completion-contracts/aui-demonstration-policy-response-v1.schema.json')),
        'idempotency_mechanism' => 'idempotency-key-header',
        'connect_timeout_seconds' => 3,
        'response_timeout_seconds' => 10,
        'retry_policy' => 'bounded-worker-retry-same-idempotency-key',
        'ambiguous_outcome_policy' => 'no-outcome-until-validated-demo-response',
        'reconciliation_mode' => 'exact-request-inspection',
        'credential_reference' => 'services.pipedream.policy_completion_token',
        'acceptance_reference' => 'testing-demo-continuation-user-authorization-2026-09-24',
        'accepted_at' => '2026-09-24T00:00:00Z',
        'accepted_by_reference' => 'testing-instance-operator',
    ],
];
