<?php

declare(strict_types=1);

namespace LBHurtado\XChange\Contracts;

use LBHurtado\XChange\Data\Cockpit\CockpitOperatorIssuanceActivityFeedbackHandoffResultData;
use LBHurtado\XChange\Data\Cockpit\CockpitOperatorIssuanceActivityFeedbackHandoffStatusProjectionData;

interface CockpitOperatorIssuanceActivityFeedbackHandoffStatusProjectorContract
{
    public function project(CockpitOperatorIssuanceActivityFeedbackHandoffResultData $result): CockpitOperatorIssuanceActivityFeedbackHandoffStatusProjectionData;
}
