/*
 * AUTO-GENERATED BY x-change:publish
 *
 * Source: packages/x-change/resources/js/utils/payCodeRelativeTime.ts
 *
 * Do not edit this published host copy directly.
 * Changes will be overwritten by php artisan x-change:publish --scope=build --force.
 */
export {
    formatAbsoluteTime as formatPayCodeAbsoluteTime,
    formatRelativeTime as formatPayCodeRelativeTime,
} from './dateTime';
