<?php

declare(strict_types=1);

it('documents campaign destination return navigation publish browser verification', function (): void {
    $packageRoot = dirname(__DIR__, 3);
    $hostRoot = dirname($packageRoot, 2);
    $report = file_get_contents($packageRoot.'/docs/ui-cockpit/reports/302-wave-47d-campaign-destination-return-navigation-publish-browser-verification.md');
    $playwright = file_get_contents($hostRoot.'/tests/playwright/cockpit-campaign-activity-navigation.spec.ts');
    $hostDetail = file_get_contents($hostRoot.'/resources/js/cockpit/pages/VoucherDetail.vue');
    $hostDistribution = file_get_contents($hostRoot.'/resources/js/cockpit/pages/DistributionWorkspace.vue');
    $cockpitCompass = file_get_contents($packageRoot.'/docs/ui-cockpit/COMPASS.md');
    $settlementCompass = file_get_contents($packageRoot.'/docs/architecture/SETTLEMENT_OS_COMPASS.md');

    expect($report)
        ->toContain('Cockpit Wave 47D')
        ->toContain('checked 58, ok 58, stale 0, missing 0, extra 0')
        ->toContain('Playwright: 1 passed')
        ->toContain('Campaign Recipient Destination Return Navigation Closure');

    expect($playwright)
        ->toContain('cockpit-voucher-detail-campaign-explorer-return-link')
        ->toContain('cockpit-voucher-detail-campaign-dashboard-return-link')
        ->toContain('cockpit-distribution-campaign-detail-return-link')
        ->toContain('cockpit-distribution-campaign-explorer-return-link')
        ->toContain('cockpit-distribution-campaign-dashboard-return-link')
        ->toContain('activity_code=PC-PLAYWRIGHT-44');

    expect($hostDetail)
        ->toContain('AUTO-GENERATED BY x-change:install')
        ->toContain('cockpit-voucher-detail-campaign-explorer-return-link');

    expect($hostDistribution)
        ->toContain('AUTO-GENERATED BY x-change:install')
        ->toContain('cockpit-distribution-campaign-detail-return-link');

    expect($cockpitCompass)
        ->toContain('Cockpit Wave 47D result: Campaign destination return navigation publish/browser verification completed');

    expect($settlementCompass)
        ->toContain('Cockpit Wave 47D — Campaign Destination Return Navigation Publish / Browser Verification');
});
