<?php

declare(strict_types=1);

it('documents the campaign recipient activity detail distribution publish and browser verification', function (): void {
    $packageRoot = dirname(__DIR__, 3);
    $hostRoot = dirname($packageRoot, 2);
    $report = file_get_contents($packageRoot.'/docs/ui-cockpit/reports/291-wave-45d-campaign-recipient-activity-detail-distribution-publish-browser-verification.md');
    $playwright = file_get_contents($hostRoot.'/tests/playwright/cockpit-campaign-activity-navigation.spec.ts');
    $hostPanel = file_get_contents($hostRoot.'/resources/js/cockpit/components/CockpitOperatorIssuanceActivityPanel.vue');
    $cockpitCompass = file_get_contents($packageRoot.'/docs/ui-cockpit/COMPASS.md');
    $settlementCompass = file_get_contents($packageRoot.'/docs/architecture/SETTLEMENT_OS_COMPASS.md');

    expect($report)
        ->toContain('Cockpit Wave 45D')
        ->toContain('checked 58, ok 58, stale 0, missing 0, extra 0')
        ->toContain('Playwright: 1 passed')
        ->toContain('Open Pay Code · campaign context · read-only')
        ->toContain('Open Distribution workspace · campaign context · read-only')
        ->toContain('Cockpit Wave 45E — Campaign Recipient Activity Detail / Distribution Context Bridge Closure');

    expect($playwright)
        ->toContain('cockpit-operator-issuance-activity-link')
        ->toContain('cockpit-operator-issuance-activity-distribution-link')
        ->toContain('campaign_recipient_id=recipient-playwright-44')
        ->toContain('PC-PLAYWRIGHT-44\/distribution')
        ->toContain('read-only');

    expect($hostPanel)
        ->toContain('AUTO-GENERATED BY x-change:install')
        ->toContain('campaign context · read-only')
        ->toContain('cockpit-operator-issuance-activity-distribution-link');

    expect($cockpitCompass)
        ->toContain('Cockpit Wave 45D result: Campaign Recipient Activity Detail / Distribution publish/browser verification completed');

    expect($settlementCompass)
        ->toContain('Cockpit Wave 45D — Campaign Recipient Activity Detail / Distribution Publish / Browser Verification');
});
