<?php

declare(strict_types=1);

it('documents the campaign recipient activity context navigation publish and browser verification', function (): void {
    $packageRoot = dirname(__DIR__, 3);
    $hostRoot = dirname($packageRoot, 2);
    $report = file_get_contents($packageRoot.'/docs/ui-cockpit/reports/286-wave-44d-campaign-recipient-activity-context-navigation-publish-browser-verification.md');
    $playwright = file_get_contents($hostRoot.'/tests/playwright/cockpit-campaign-activity-navigation.spec.ts');
    $hostPanel = file_get_contents($hostRoot.'/resources/js/cockpit/components/CockpitOperatorIssuanceActivityPanel.vue');
    $cockpitCompass = file_get_contents($packageRoot.'/docs/ui-cockpit/COMPASS.md');
    $settlementCompass = file_get_contents($packageRoot.'/docs/architecture/SETTLEMENT_OS_COMPASS.md');

    expect($report)
        ->toContain('Cockpit Wave 44D')
        ->toContain('checked 58, ok 58, stale 0, missing 0, extra 0')
        ->toContain('tests/playwright/cockpit-campaign-activity-navigation.spec.ts')
        ->toContain('Open in Explorer · campaign context')
        ->toContain('Return to Campaign Dashboard · read-only')
        ->toContain('Cockpit Wave 44E — Campaign Recipient Activity Context Navigation Closure');

    expect($playwright)
        ->toContain('dashboard campaign activity card preserves recipient context in read-only navigation links')
        ->toContain('recipient-playwright-44')
        ->toContain('campaign_recipient_id=recipient-playwright-44')
        ->toContain('provider_payload');

    expect($hostPanel)
        ->toContain('AUTO-GENERATED BY x-change:install')
        ->toContain('campaign context')
        ->toContain('cockpit-operator-issuance-activity-campaign-dashboard-link');

    expect($cockpitCompass)
        ->toContain('Cockpit Wave 44D result: Campaign Recipient Activity context navigation publish/browser verification completed');

    expect($settlementCompass)
        ->toContain('Cockpit Wave 44D — Campaign Recipient Activity Context Navigation Publish / Browser Verification');
});
