<?php

declare(strict_types=1);

it('documents the campaign recipient detail distribution publish browser verification', function (): void {
    $packageRoot = dirname(__DIR__, 3);
    $hostRoot = dirname($packageRoot, 2);
    $report = file_get_contents($packageRoot.'/docs/ui-cockpit/reports/297-wave-46e-campaign-recipient-detail-distribution-publish-browser-verification.md');
    $playwright = file_get_contents($hostRoot.'/tests/playwright/cockpit-campaign-activity-navigation.spec.ts');
    $hostDetail = file_get_contents($hostRoot.'/resources/js/cockpit/pages/VoucherDetail.vue');
    $hostDistribution = file_get_contents($hostRoot.'/resources/js/cockpit/pages/DistributionWorkspace.vue');
    $cockpitCompass = file_get_contents($packageRoot.'/docs/ui-cockpit/COMPASS.md');
    $settlementCompass = file_get_contents($packageRoot.'/docs/architecture/SETTLEMENT_OS_COMPASS.md');

    expect($report)
        ->toContain('Cockpit Wave 46E')
        ->toContain('checked 58, ok 58, stale 0, missing 0, extra 0')
        ->toContain('Playwright: 1 passed')
        ->toContain('Pay Code Detail with a `Campaign recipient context` card')
        ->toContain('Cockpit Wave 46F — Campaign Recipient Detail / Distribution Context Rendering Closure');

    expect($playwright)
        ->toContain('cockpit-voucher-detail-campaign-navigation-context')
        ->toContain('cockpit-distribution-campaign-navigation-context')
        ->toContain('recipient-playwright-44')
        ->toContain('campaign-navigation-read-only');

    expect($hostDetail)
        ->toContain('AUTO-GENERATED BY x-change:install')
        ->toContain('cockpit-voucher-detail-campaign-navigation-context');

    expect($hostDistribution)
        ->toContain('AUTO-GENERATED BY x-change:install')
        ->toContain('cockpit-distribution-campaign-navigation-context');

    expect($cockpitCompass)
        ->toContain('Cockpit Wave 46E result: Campaign Recipient Detail / Distribution publish/browser verification completed');

    expect($settlementCompass)
        ->toContain('Cockpit Wave 46E — Campaign Recipient Detail / Distribution Publish / Browser Verification');
});
