<?php

declare(strict_types=1);

it('documents cockpit durable summary projection publish and browser verification', function (): void {
    $packageRoot = dirname(__DIR__, 3);
    $hostRoot = dirname($packageRoot, 2);
    $report = file_get_contents($packageRoot.'/docs/architecture/execution-engine/reports/022-cockpit-durable-summary-projection-publish-browser-verification.md');
    $playwright = file_get_contents($hostRoot.'/tests/playwright/cockpit-execution-projection.spec.ts');
    $hostPanel = file_get_contents($hostRoot.'/resources/js/cockpit/components/CockpitRecentActivityPanel.vue');
    $hostDashboard = file_get_contents($hostRoot.'/resources/js/cockpit/pages/Dashboard.vue');
    $hostTypes = file_get_contents($hostRoot.'/resources/js/cockpit/types.ts');
    $executionCompass = file_get_contents($packageRoot.'/docs/architecture/execution-engine/EXECUTION_ENGINE_COMPASS.md');
    $settlementCompass = file_get_contents($packageRoot.'/docs/architecture/SETTLEMENT_OS_COMPASS.md');
    $cockpitCompass = file_get_contents($packageRoot.'/docs/ui-cockpit/COMPASS.md');

    expect($report)
        ->toContain('Execution Integration Slice 15')
        ->toContain('checked 60, ok 60, stale 0, missing 0, extra 0')
        ->toContain('npm run test:browser -- tests/playwright/cockpit-execution-projection.spec.ts')
        ->toContain('Durable summary evidence')
        ->toContain('Execution Integration Slice 16');

    expect($playwright)
        ->toContain('cockpit-activity-projection-status')
        ->toContain('execution.handoff.summary.recorded')
        ->toContain('durable_summary_evidence_available');

    expect($hostPanel)
        ->toContain('AUTO-GENERATED BY x-change:install')
        ->toContain('cockpit-activity-projection-status')
        ->toContain('projection_targets');

    expect($hostDashboard)
        ->toContain('AUTO-GENERATED BY x-change:install')
        ->toContain('projection_status');

    expect($hostTypes)
        ->toContain('AUTO-GENERATED BY x-change:install')
        ->toContain('projection_targets?: string[]');

    expect($executionCompass)
        ->toContain('Cockpit Durable Summary Projection Publish / Browser Verification')
        ->toContain('reports/022-cockpit-durable-summary-projection-publish-browser-verification.md');

    expect($settlementCompass)
        ->toContain('Execution Integration Slice 15 — Cockpit Durable Summary Projection Publish / Browser Verification');

    expect($cockpitCompass)
        ->toContain('Execution Integration Slice 15 — Cockpit Durable Summary Projection Publish / Browser Verification');
});
