<?php

declare(strict_types=1);

it('documents runtime profile compact diagnostics slice 1', function (): void {
    $packageRoot = dirname(__DIR__, 3);

    $report = file_get_contents($packageRoot.'/docs/ui-cockpit/reports/639-runtime-profile-compact-diagnostics-slice-1.md');
    $page = file_get_contents($packageRoot.'/resources/js/cockpit/pages/RuntimeProfile.vue');
    $frontendTest = file_get_contents($packageRoot.'/tests/frontend/cockpit/CockpitRuntimeProfileDiagnostics.test.ts');
    $compass = file_get_contents($packageRoot.'/docs/ui-cockpit/COMPASS.md');
    $settlementCompass = file_get_contents($packageRoot.'/docs/architecture/SETTLEMENT_OS_COMPASS.md');

    expect($report)
        ->toContain('Runtime Profile Compact Diagnostics — Slice 1')
        ->toContain('slim operational header')
        ->toContain('Presentation-only runtime-profile shell compression')
        ->and($page)->toContain('data-testid="cockpit-runtime-profile-header"')
        ->and($page)->toContain('data-testid="cockpit-runtime-profile-header-facts"')
        ->and($page)->toContain('Runtime profile context')
        ->and($frontendTest)->toContain("expect(header.classes()).toContain('py-3')")
        ->and($frontendTest)->toContain("expect(context.attributes('open')).toBeUndefined()")
        ->and($compass)->toContain('Runtime Profile Compact Diagnostics — Slice 1')
        ->and($settlementCompass)->toContain('Runtime Profile Compact Diagnostics — Slice 1');
});

it('documents runtime profile compact diagnostics slice 2', function (): void {
    $packageRoot = dirname(__DIR__, 3);

    $report = file_get_contents($packageRoot.'/docs/ui-cockpit/reports/640-runtime-profile-compact-diagnostics-slice-2.md');
    $page = file_get_contents($packageRoot.'/resources/js/cockpit/pages/RuntimeProfile.vue');
    $frontendTest = file_get_contents($packageRoot.'/tests/frontend/cockpit/CockpitRuntimeProfileDiagnostics.test.ts');
    $compass = file_get_contents($packageRoot.'/docs/ui-cockpit/COMPASS.md');
    $settlementCompass = file_get_contents($packageRoot.'/docs/architecture/SETTLEMENT_OS_COMPASS.md');

    expect($report)
        ->toContain('Runtime Profile Compact Diagnostics — Slice 2')
        ->toContain('closed count-bearing disclosure')
        ->toContain('Presentation-only component-inventory compression')
        ->and($page)->toContain('data-testid="cockpit-runtime-profile-components"')
        ->and($page)->toContain('{{ components.length }} components')
        ->and($frontendTest)->toContain("expect(componentPanel.attributes('open')).toBeUndefined()")
        ->and($frontendTest)->toContain("expect(componentRows[0].classes()).toContain('p-3')")
        ->and($compass)->toContain('Runtime Profile Compact Diagnostics — Slice 2')
        ->and($settlementCompass)->toContain('Runtime Profile Compact Diagnostics — Slice 2');
});

it('documents runtime profile compact diagnostics slice 3 closure', function (): void {
    $packageRoot = dirname(__DIR__, 3);

    $report = file_get_contents($packageRoot.'/docs/ui-cockpit/reports/641-runtime-profile-compact-diagnostics-slice-3-closure.md');
    $page = file_get_contents($packageRoot.'/resources/js/cockpit/pages/RuntimeProfile.vue');
    $frontendTest = file_get_contents($packageRoot.'/tests/frontend/cockpit/CockpitRuntimeProfileDiagnostics.test.ts');
    $hostPage = file_get_contents(dirname($packageRoot, 2).'/resources/js/cockpit/pages/RuntimeProfile.vue');
    $compass = file_get_contents($packageRoot.'/docs/ui-cockpit/COMPASS.md');
    $settlementCompass = file_get_contents($packageRoot.'/docs/architecture/SETTLEMENT_OS_COMPASS.md');

    expect($report)
        ->toContain('Runtime Profile Compact Diagnostics — Slice 3 / Closure')
        ->toContain('matching closed flag summaries')
        ->toContain('Presentation-only safety-panel compression closure')
        ->and($page)->toContain('data-testid="cockpit-runtime-profile-safety-grid"')
        ->and($page)->toContain('{{ safetyEntries.length }} flags')
        ->and($page)->toContain('{{ runtimeSafetyEntries.length }} flags')
        ->and($frontendTest)->toContain("expect(pageSafety.attributes('open')).toBeUndefined()")
        ->and($frontendTest)->toContain("expect(runtimeSafety.attributes('open')).toBeUndefined()")
        ->and($hostPage)->toContain('AUTO-GENERATED BY x-change:install')
        ->and($compass)->toContain('Runtime Profile Compact Diagnostics — Slice 3 Closure')
        ->and($settlementCompass)->toContain('Runtime Profile Compact Diagnostics — Slice 3');
});
