<?php

declare(strict_types=1);

it('documents voucher detail browser feedback refinement slice 1', function (): void {
    $packageRoot = dirname(__DIR__, 3);

    $report = file_get_contents($packageRoot.'/docs/ui-cockpit/reports/637-voucher-detail-browser-feedback-refinement-slice-1.md');
    $audit = file_get_contents($packageRoot.'/resources/js/cockpit/components/CockpitVoucherAuditPanel.vue');
    $frontendTest = file_get_contents($packageRoot.'/tests/frontend/cockpit/CockpitVoucherDetailFoundation.test.ts');
    $compass = file_get_contents($packageRoot.'/docs/ui-cockpit/COMPASS.md');
    $settlementCompass = file_get_contents($packageRoot.'/docs/architecture/SETTLEMENT_OS_COMPASS.md');

    expect($report)
        ->toContain('Voucher Detail Browser Feedback Refinement — Slice 1')
        ->toContain('one scan row')
        ->toContain('Presentation-only audit-summary compression')
        ->and($audit)->toContain('data-testid="cockpit-voucher-audit-summary"')
        ->and($audit)->toContain('disabled follow-ups')
        ->and($audit)->not->toContain('View details')
        ->and($frontendTest)->toContain("expect(wrapper.find('[data-testid=\"cockpit-voucher-audit-panel\"]').classes()).toContain('py-2.5')")
        ->and($compass)->toContain('Voucher Detail Browser Feedback Refinement — Slice 1')
        ->and($settlementCompass)->toContain('Voucher Detail Browser Feedback Refinement — Slice 1');
});

it('documents voucher detail browser feedback refinement slice 2 closure', function (): void {
    $packageRoot = dirname(__DIR__, 3);

    $report = file_get_contents($packageRoot.'/docs/ui-cockpit/reports/638-voucher-detail-browser-feedback-refinement-slice-2-closure.md');
    $page = file_get_contents($packageRoot.'/resources/js/cockpit/pages/VoucherDetail.vue');
    $frontendTest = file_get_contents($packageRoot.'/tests/frontend/cockpit/CockpitVoucherDetailHydration.test.ts');
    $hostPage = file_get_contents(dirname($packageRoot, 2).'/resources/js/cockpit/pages/VoucherDetail.vue');
    $compass = file_get_contents($packageRoot.'/docs/ui-cockpit/COMPASS.md');
    $settlementCompass = file_get_contents($packageRoot.'/docs/architecture/SETTLEMENT_OS_COMPASS.md');

    expect($report)
        ->toContain('Voucher Detail Browser Feedback Refinement — Slice 2 / Closure')
        ->toContain('single canonical Connected services disclosure')
        ->toContain('Presentation-only service-summary rationalization')
        ->and($page)->toContain('data-testid="cockpit-voucher-detail-primary-evidence-readiness"')
        ->and($page)->toContain('data-testid="cockpit-voucher-detail-primary-evidence-readiness-reason"')
        ->and($page)->not->toContain('data-testid="cockpit-voucher-integration-summary-panel"')
        ->and($frontendTest)->toContain("expect(wrapper.find('[data-testid=\"cockpit-voucher-integration-summary-panel\"]').exists()).toBe(false)")
        ->and($hostPage)->toContain('AUTO-GENERATED BY x-change:install')
        ->and($compass)->toContain('Voucher Detail Browser Feedback Refinement — Slice 2 Closure')
        ->and($settlementCompass)->toContain('Voucher Detail Browser Feedback Refinement — Slice 2');
});
